name: Android Debug Build

env:
  main_project_module: app

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: 17
        distribution: 'corretto'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create local.properties
      run: touch local.properties

    - name: Build Debug APK
      run: ./gradlew assembleDebug --warning-mode all

    - name: Upload Debug arm64-v8a
      uses: actions/upload-artifact@v4
      with:
        name: ytdlnis-debug-arm64-v8a
        path: app/build/outputs/apk/debug/*arm64*.apk

    - name: Upload Debug armeabi-v7a
      uses: actions/upload-artifact@v4
      with:
        name: ytdlnis-debug-armeabi-v7a
        path: app/build/outputs/apk/debug/*armeabi*.apk

    - name: Upload Debug universal
      uses: actions/upload-artifact@v4
      with:
        name: ytdlnis-debug-universal
        path: app/build/outputs/apk/debug/*universal*.apk

    - name: Upload Debug x86
      uses: actions/upload-artifact@v4
      with:
        name: ytdlnis-debug-x86
        path: app/build/outputs/apk/debug/*x86-*.apk

    - name: Upload Debug x86_64
      uses: actions/upload-artifact@v4
      with:
        name: ytdlnis-debug-x86_64
        path: app/build/outputs/apk/debug/*x86_64*.apk
